(()=>{
const q=id=>document.getElementById(id),canvas=q('map'),ctx=canvas.getContext('2d');
let data=null,timer=null,bounds=null,loading=false;
const palette=['#075fc8','#aa5a08','#7546aa','#00796b','#b73650','#4c617a'];
function stop(){if(timer)clearInterval(timer);timer=null;q('play').textContent='Odtwarzaj';}
function draw(){if(!data)return;const k=Number(q('frame').value),f=data.frames[k],w=canvas.clientWidth,h=canvas.clientHeight,d=window.devicePixelRatio||1;canvas.width=w*d;canvas.height=h*d;ctx.setTransform(d,0,0,d,0,0);ctx.clearRect(0,0,w,h);const l=52,r=w-24,t=16,b=h-46;const sx=x=>l+(x-bounds.x0)/(bounds.x1-bounds.x0)*(r-l),sy=y=>b-(y-bounds.y0)/(bounds.y1-bounds.y0)*(b-t);ctx.font='12px Segoe UI';ctx.lineWidth=1;for(let i=0;i<5;i++){const x=bounds.x0+i*(bounds.x1-bounds.x0)/4,y=bounds.y0+i*(bounds.y1-bounds.y0)/4;ctx.strokeStyle='#e2e8f0';ctx.beginPath();ctx.moveTo(sx(x),t);ctx.lineTo(sx(x),b);ctx.moveTo(l,sy(y));ctx.lineTo(r,sy(y));ctx.stroke();ctx.fillStyle='#536579';ctx.textAlign='center';ctx.fillText(x.toFixed(0),sx(x),b+18);ctx.textAlign='right';ctx.fillText(y.toFixed(0),l-8,sy(y)+4);}ctx.fillStyle='#203044';ctx.textAlign='center';ctx.fillText('X [m]',(l+r)/2,h-8);ctx.save();ctx.translate(14,(t+b)/2);ctx.rotate(-Math.PI/2);ctx.fillText('Y [m]',0,0);ctx.restore();const histories=new Map();for(let i=0;i<=k;i++){for(const tr of data.frames[i].tracks){if(!histories.has(tr.id))histories.set(tr.id,[]);histories.get(tr.id).push(tr);}}for(const [id,points]of histories){ctx.strokeStyle=palette[(id-1)%palette.length];ctx.lineWidth=1.5;ctx.beginPath();points.forEach((p,i)=>{if(i===0)ctx.moveTo(sx(p.x),sy(p.y));else ctx.lineTo(sx(p.x),sy(p.y));});ctx.stroke();}ctx.fillStyle='#9ba9b8';for(const p of f.points){ctx.beginPath();ctx.arc(sx(p.x),sy(p.y),2,0,Math.PI*2);ctx.fill();}if(q('truth').checked){ctx.strokeStyle='#263747';ctx.lineWidth=1;for(const p of f.truth){const x=sx(p.x),y=sy(p.y);ctx.beginPath();ctx.moveTo(x-4,y-4);ctx.lineTo(x+4,y+4);ctx.moveTo(x+4,y-4);ctx.lineTo(x-4,y+4);ctx.stroke();}}for(const p of f.tracks){const color=palette[(p.id-1)%palette.length];ctx.strokeStyle=color;ctx.setLineDash([4,3]);ctx.beginPath();ctx.moveTo(sx(p.x),sy(p.y));ctx.lineTo(sx(p.predicted.x),sy(p.predicted.y));ctx.stroke();ctx.setLineDash([]);ctx.fillStyle=color;ctx.beginPath();ctx.arc(sx(p.x),sy(p.y),4,0,Math.PI*2);ctx.fill();ctx.fillStyle='#203044';ctx.textAlign='left';ctx.fillText('#'+p.id,sx(p.x)+7,sy(p.y)-7);}q('time').textContent=`Klatka ${k+1}/40 · ${f.t.toFixed(1)} s`;q('tracks').textContent=f.tracks.length;q('echoes').textContent=f.points.length;q('mode').textContent=data.model==='timdr'?'TIMDR':'CV';q('rows').replaceChildren();for(const p of f.tracks){const tr=document.createElement('tr');for(const text of ['#'+p.id,p.x.toFixed(1),p.y.toFixed(1),data.model==='timdr'?p.score.toFixed(2):'—']){const td=document.createElement('td');td.textContent=text;tr.appendChild(td);}q('rows').appendChild(tr);}}
async function run(){if(loading)return;loading=true;stop();q('run').disabled=true;q('status').textContent='Przetwarzanie przez tracker…';try{const params=new URLSearchParams({model:q('model').value,scene:q('scene').value,count:q('count').value});const response=await fetch('/api/demo?'+params);if(!response.ok)throw Error('Nie udało się uruchomić analizy');data=await response.json();const points=data.frames.flatMap(f=>[...f.points,...f.tracks.flatMap(p=>[p,p.predicted])]);bounds={x0:Math.floor(Math.min(...points.map(p=>p.x))/10)*10-5,x1:Math.ceil(Math.max(...points.map(p=>p.x))/10)*10+5,y0:Math.floor(Math.min(...points.map(p=>p.y))/10)*10-5,y1:Math.ceil(Math.max(...points.map(p=>p.y))/10)*10+5};q('frame').value=0;q('frame').disabled=false;q('play').disabled=false;q('status').textContent=`Gotowe: 40 klatek · ${data.objects} obiektów w generatorze · ${data.model==='timdr'?'TIMDR':'CV'}`;draw();}catch(e){q('status').textContent=e.message;}finally{loading=false;q('run').disabled=false;}}
q('run').addEventListener('click',run);q('play').addEventListener('click',()=>{if(timer){stop();return;}if(Number(q('frame').value)===39)q('frame').value=0;q('play').textContent='Pauza';timer=setInterval(()=>{let k=Number(q('frame').value);if(k>=39){stop();return;}q('frame').value=k+1;draw();},180);});q('frame').addEventListener('input',()=>{stop();draw();});q('truth').addEventListener('change',draw);new ResizeObserver(draw).observe(canvas);window.addEventListener('pagehide',stop);run();
})();
